### ISSUE TITLE
Relaese with new MRML cross compilation gems

### ISSUE THREAD

**Issue by henrikbjorn** [oddcamp/mrml-rails#47]
ruby-mrml now precompiles the extensions. A new release with those would be great (if it is needed at all) or an update to the readme.

**Comment by paulgoetze** [comment]
@henrikbjorn I think you would not need a new version of mrml-rails. Updating the mrml dependency should be enough to make it work, i.e. try

`bundle update mrml-rails`

to pull in the new mrml version.
